# Generated by Django 3.2.8 on 2023-09-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('modeel', models.CharField(max_length=20, unique=True)),
                ('file', models.FileField(upload_to='store/excel/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=200, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
            ],
        ),
    ]
