# Generated by Django 3.2.8 on 2023-09-01 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0002_alter_student_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='modeel',
        ),
        migrations.AddField(
            model_name='store',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
