# Generated by Django 3.2.8 on 2023-09-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0003_auto_20230901_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='registration_number',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='surname',
            new_name='date',
        ),
        migrations.AddField(
            model_name='student',
            name='total_amount',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
