# Generated by Django 3.2.8 on 2023-09-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0004_auto_20230901_1149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Buyerdata',
        ),
        migrations.RemoveField(
            model_name='store',
            name='date',
        ),
    ]
